export type Material = { id: string; title: string; subtitle: string; category: string; topic: string; pages: number; owned: boolean; badge?: string; progress?: number; price?: string; cover: number; description: string };
export const materials: Material[] = [
 {id:'80-casos',title:'80 Casos Visuais de Psicodiagnóstico',subtitle:'Coleção essencial',category:'Casos visuais',topic:'Psicodiagnóstico',pages:320,owned:true,badge:'MAIS ACESSADO',progress:34,cover:1,description:'Raciocínio clínico, hipóteses e diferenciação em uma experiência visual.'},
 {id:'10-mapas',title:'10 Mapas Visuais do Processo Psicodiagnóstico',subtitle:'Mapas visuais',category:'Mapas e guias',topic:'Processo clínico',pages:48,owned:true,progress:62,cover:2,description:'Uma visão clara e organizada de cada etapa do processo psicodiagnóstico.'},
 {id:'paineis',title:'10 Painéis Visuais de Diferenciação Clínica',subtitle:'Painéis visuais',category:'Mapas e guias',topic:'Diferenciação clínica',pages:58,owned:true,badge:'ATUALIZADO',cover:3,description:'Compare sinais, hipóteses e caminhos de investigação de forma visual.'},
 {id:'checklist',title:'Checklist Visual de Organização do Caso',subtitle:'Ferramenta clínica',category:'Bônus exclusivos',topic:'Organização',pages:16,owned:true,badge:'BÔNUS',cover:4,description:'Um apoio prático para organizar informações essenciais de um caso.'},
 {id:'entrevista',title:'Guia Visual da Entrevista Inicial',subtitle:'Guia visual',category:'Mapas e guias',topic:'Entrevista',pages:42,owned:true,cover:5,description:'Orientações visuais para a escuta e estruturação da entrevista inicial.'},
 {id:'devolutiva',title:'Guia Visual da Devolutiva Clínica',subtitle:'Guia visual',category:'Mapas e guias',topic:'Devolutiva',pages:36,owned:true,cover:6,description:'Da integração dos achados à comunicação clínica responsável.'},
 {id:'exame-mental',title:'30 Mapas Visuais do Exame do Estado Mental',subtitle:'Coleção de mapas',category:'Mapas e guias',topic:'Exame mental',pages:124,owned:true,badge:'NOVO',cover:7,description:'Explore funções psíquicas com mapas didáticos e conexões clínicas.'},
 {id:'flashcards',title:'Flashcards Visuais do Exame Mental',subtitle:'Flashcards',category:'Bônus exclusivos',topic:'Exame mental',pages:80,owned:true,badge:'NOVO',cover:8,description:'Revise conceitos fundamentais por meio de cartões visuais.'},
 {id:'ansiedade',title:'Casos Visuais: Ansiedade e Diferenciação',subtitle:'Casos visuais',category:'Casos visuais',topic:'Ansiedade',pages:54,owned:false,badge:'NOVIDADE',price:'R$ 49,90',cover:9,description:'Investigue quadros de ansiedade com casos comentados e pistas visuais.'},
 {id:'tdah',title:'Mapas Visuais: TDAH na Avaliação',subtitle:'Nova coleção',category:'Mapas e guias',topic:'TDAH',pages:64,owned:false,badge:'NOVO',price:'R$ 59,90',cover:10,description:'Mapas para apoiar o raciocínio diferencial em contextos de avaliação.'},
 {id:'trauma',title:'20 Casos Visuais: Trauma e Dissociação',subtitle:'Aprofundamento',category:'Casos visuais',topic:'Trauma',pages:92,owned:false,price:'R$ 79,90',cover:11,description:'Novas perspectivas clínicas apresentadas em casos visuais.'},
];
export const topics = ['Todos','Ansiedade','Depressão','TDAH','TOC','Bipolaridade','Trauma','TEA','Psicoses','Transtornos Alimentares','Personalidade','Neurocognitivo','Outros'];
