import { createFileRoute, Link } from '@tanstack/react-router';
import { ArrowRight, Play, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { AppShell } from '@/components/AppShell';
import { Shelf } from '@/components/MaterialCard';
import { materials } from '@/lib/catalog';
import hero from '@/assets/clinical-hero.jpg';
export const Route=createFileRoute('/')({head:()=>({meta:[{title:'Início | Psicodiagnóstico Visual'},{name:'description',content:'Explore sua biblioteca visual de Psicologia, casos clínicos, mapas e guias.'},{property:'og:title',content:'Psicodiagnóstico Visual — Biblioteca'},{property:'og:description',content:'Uma biblioteca visual premium de materiais de Psicologia.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Home});
function Home(){const owned=materials.filter(x=>x.owned),shop=materials.filter(x=>!x.owned);return <AppShell><div className="home-hero" style={{backgroundImage:`linear-gradient(90deg,var(--background) 0%,color-mix(in oklab,var(--background) 94%,transparent) 27%,transparent 76%),linear-gradient(0deg,var(--background),transparent 45%),url(${hero})`}}><div className="page-wrap hero-content"><span className="hero-kicker"><span/> SUA BIBLIOTECA VISUAL</span><h1>80 Casos Visuais de <em>Psicodiagnóstico</em></h1><p>Raciocínio clínico, hipóteses e diferenciação em uma experiência visual.</p><div className="hero-actions"><Button size="lg" asChild><Link to="/material/$id/ler" params={{id:'80-casos'}}><Play fill="currentColor"/> Continuar estudando</Link></Button><Button size="lg" variant="outline" asChild><Link to="/material/$id" params={{id:'80-casos'}}>Ver material <ArrowRight/></Link></Button></div><div className="hero-meta"><span>01 / 04</span><span className="hero-meter"><i/></span><span>COLEÇÃO EM DESTAQUE</span></div></div></div><div className="page-wrap home-content"><Shelf title="Continue de onde parou" items={owned.filter(x=>x.progress!==undefined)} more="/biblioteca" wide/><Shelf title="Sua biblioteca" items={owned} more="/biblioteca"/><Shelf title="Casos visuais" items={[...owned.slice(0,1),...shop.filter(x=>x.category==='Casos visuais')]} more="/casos" wide/><Shelf title="Mapas e guias" items={owned.filter(x=>x.category==='Mapas e guias')} more="/mapas"/><Shelf title="Bônus exclusivos" items={owned.filter(x=>x.category==='Bônus exclusivos')} more="/bonus"/><Shelf title="Novidades" items={materials.filter(x=>x.badge==='NOVO'||x.badge==='NOVIDADE')} more="/atualizacoes"/><Shelf title="Recomendados para você" items={shop} more="/loja"/><div className="explore-band"><span className="eyebrow"><Sparkles size={14}/> EXPANDA SUA BIBLIOTECA</span><h2>Novas perspectivas para ir ainda mais longe.</h2><p>Explore materiais visuais criados para acompanhar sua jornada de estudo.</p><Button asChild><Link to="/loja">Explore mais produtos <ArrowRight/></Link></Button></div></div></AppShell>}
