import { Link, useNavigate, useRouterState } from '@tanstack/react-router';
import { Bell, BookOpen, Compass, Heart, Home, Menu, Search, ShoppingBag, UserRound, X, LogOut, ChevronDown } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { registerAppWorker } from '@/lib/pwa';

const nav = [{to:'/',label:'Início'},{to:'/biblioteca',label:'Minha biblioteca'},{to:'/casos',label:'Casos visuais'},{to:'/mapas',label:'Mapas'},{to:'/bonus',label:'Bônus'},{to:'/atualizacoes',label:'Atualizações'},{to:'/loja',label:'Loja'}] as const;
export function Brand() { return <Link to="/" className="brand flex shrink-0 items-center gap-3"><span className="brand-mark"><span className="brand-mark-inner">Ψ</span></span><span className="brand-type">PSICODIAGNÓSTICO<span>VISUAL</span></span></Link> }
export function AppShell({children}:{children:React.ReactNode}) {
 const [menu,setMenu]=useState(false); const [account,setAccount]=useState(false); const [notifications,setNotifications]=useState(false); const [installPrompt,setInstallPrompt]=useState<Event|null>(null); const [ios,setIos]=useState(false); const [installed,setInstalled]=useState(false); const [online,setOnline]=useState(true); const [email,setEmail]=useState<string|null>(null);
 const navigate=useNavigate(); const path=useRouterState({select:s=>s.location.pathname});
 useEffect(()=>{ registerAppWorker(); setOnline(navigator.onLine); setIos(/iPhone|iPad|iPod/.test(navigator.userAgent)); setInstalled(window.matchMedia('(display-mode: standalone)').matches); const onOnline=()=>setOnline(true), onOffline=()=>setOnline(false); const onInstall=(e:Event)=>{e.preventDefault();setInstallPrompt(e)}; window.addEventListener('online',onOnline);window.addEventListener('offline',onOffline);window.addEventListener('beforeinstallprompt',onInstall); supabase.auth.getUser().then(({data})=>setEmail(data.user?.email??null)); const {data:{subscription}}=supabase.auth.onAuthStateChange((_,session)=>setEmail(session?.user.email??null)); return ()=>{window.removeEventListener('online',onOnline);window.removeEventListener('offline',onOffline);window.removeEventListener('beforeinstallprompt',onInstall);subscription.unsubscribe()}; },[]);
 async function logout(){await supabase.auth.signOut();setAccount(false);navigate({to:'/entrar'})}
 return <div className="min-h-screen bg-background text-foreground">
 <header className="site-header"><div className="header-inner"><Brand/><nav className="desktop-nav">{nav.map(n=><Link key={n.to} to={n.to} className={path===n.to?'active':''}>{n.label}</Link>)}</nav><div className="header-actions"><Button variant="ghost" size="icon" title="Buscar" aria-label="Buscar" onClick={()=>navigate({to:'/buscar'})}><Search/></Button><div className="relative"><Button variant="ghost" size="icon" title="Notificações" aria-label="Notificações" onClick={()=>setNotifications(!notifications)}><Bell/></Button>{notifications&&<div className="header-popover right-0"><div className="eyebrow mb-3">NOTIFICAÇÕES</div><p className="text-sm text-muted-foreground">Você está em uma prévia da biblioteca. As notificações da sua conta aparecerão aqui.</p><Link to="/atualizacoes" onClick={()=>setNotifications(false)} className="text-sm text-accent mt-4 block">Ver atualizações →</Link></div>}</div><div className="relative"><Button variant="ghost" className="avatar-button" aria-label="Abrir menu da conta" onClick={()=>setAccount(!account)}><span className="avatar-circle"><UserRound size={17}/></span><ChevronDown size={14} className="hidden lg:block"/></Button>{account&&<div className="header-popover right-0 account-menu"><p className="text-xs text-muted-foreground pb-3 border-b border-border truncate">{email??'Visitante'}</p>{[['Minha conta','/conta'],['Minhas compras','/biblioteca'],['Favoritos','/favoritos'],['Ajuda','/ajuda']].map(([label,to])=><Link key={to} to={to as '/conta'} onClick={()=>setAccount(false)}>{label}</Link>)}{email?<Button variant="ghost" onClick={logout}><LogOut size={15}/> Sair</Button>:<Link to="/entrar" onClick={()=>setAccount(false)}>Entrar</Link>}</div>}</div><Button variant="ghost" size="icon" className="lg:hidden" aria-label="Abrir menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</Button></div></div>{menu&&<div className="mobile-menu">{nav.map(n=><Link key={n.to} to={n.to} onClick={()=>setMenu(false)}>{n.label}</Link>)}</div>}</header>
 {!online&&<div className="offline-banner">Você está offline. O aplicativo continua disponível; materiais protegidos precisam de conexão.</div>}
 <main>{children}</main>
 <footer className="site-footer"><div className="page-wrap"><div className="footer-top"><Brand/><div className="footer-links"><Link to="/ajuda">Suporte</Link><Link to="/termos">Termos</Link><Link to="/privacidade">Privacidade</Link><Link to="/politica-de-uso">Política de uso</Link></div></div><p>Material educacional. Não substitui formação profissional, supervisão, avaliação individualizada ou normas aplicáveis à prática psicológica.</p><span className="copyright">© {new Date().getFullYear()} Psicodiagnóstico Visual</span></div></footer>
 <nav className="bottom-nav"><Link to="/" className={path==='/'?'selected':''}><Home/><span>Início</span></Link><Link to="/biblioteca" className={path==='/biblioteca'?'selected':''}><BookOpen/><span>Biblioteca</span></Link><Link to="/buscar" className={path==='/buscar'?'selected':''}><Compass/><span>Explorar</span></Link><Link to="/loja" className={path==='/loja'?'selected':''}><ShoppingBag/><span>Loja</span></Link><Link to="/conta" className={path==='/conta'?'selected':''}><UserRound/><span>Perfil</span></Link></nav>
 {!installed&&(installPrompt||ios)&&<div className="install-note">{installPrompt?<><span>Leve sua biblioteca com você.</span><Button size="sm" onClick={async()=>{await (installPrompt as Event & {prompt:()=>Promise<void>}).prompt();setInstallPrompt(null)}}>Instalar aplicativo</Button></>:<><span>Para instalar no iPhone, toque em Compartilhar e depois em Adicionar à Tela de Início.</span><Button variant="ghost" size="icon" aria-label="Fechar" onClick={()=>setInstalled(true)}><X/></Button></>}</div>}
 </div>
}
